main: nl.parrotlync.discovsignatures.DiscovSignatures
name: ${artifactId}
version: ${version}
description: ${description}
api-version: 1.15
author: ParrotLync
depend: [DiscovSuite]
commands:
  signatures:
    description: Main DiscovSignatures command
    usage: /signatures
    aliases: [ds]
permissions:
  discovsignatures.receive:
    default: op
    description: Permission to receive signatures
  discovsignatures.send:
    default: op
    description: Permission to send signatures